/**
 * Copyright 2016 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.morethan.jmhreport.gradle.task

import io.morethan.jmhreport.extract
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.zip.ZipInputStream

/**
 * Task for generating a jmh-report from the default report location (configured through JmhReportExtension)
 **/
abstract class JmhReportTask : DefaultTask() {
    @get:InputFile
    abstract val jmhResultPath: RegularFileProperty

    @get:OutputDirectory
    abstract val jmhReportOutput: DirectoryProperty

    init {
        group = "Reporting"
        description = "Create an HTML report for the latest JMH results."
    }

    @TaskAction
    fun generateReport() {
        val reportFile =
            jmhResultPath.orNull?.asFile
                ?: throw IllegalStateException("Input file is required for report generation")

        val outputFolder =
            jmhReportOutput.orNull
                ?: throw IllegalStateException("Output folder is required for report generation")

        check(reportFile.exists()) {
            "Input '${reportFile.canonicalFile}' does not exists!"
        }

        val jmhVisualizerZip =
            javaClass.getResourceAsStream("/jmh-visualizer.zip")
                ?: throw IllegalStateException("Could not find jmh-visualizer.zip")

        ZipInputStream(jmhVisualizerZip).use { zipStream ->
            zipStream.extract(outputFolder.asFile)
        }

        val runName = reportFile.nameWithoutExtension
        val providedJsFile = outputFolder.file("provided.js").asFile
        providedJsFile.printWriter().use { writer ->
            writer.println(
                "// provided.js - generated by gradle-jmh-report, " +
                    (SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS", Locale.getDefault()).format(Date())),
            )
            writer.println()
            writer.println("var providedBenchmarks = ['$runName'];")
            writer.println()
            writer.println("var providedBenchmarkStore = {")
            writer.println("'$runName': ")
            reportFile.forEachLine { line -> writer.println(line) }
            writer.println("};")
        }
        println("JMH Report generated, please open: file://$outputFolder/index.html")
    }
}
